name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build default
        run: make
      - name: Check artifact
        run: test -f build/lib/udr-pak.so && echo "artifact present"
      - name: Build with SDKDIR override (if set)
        env:
          SDKDIR: ${{ secrets.SDKDIR }}
        run: if [ -n "${SDKDIR}" ]; then make SDKDIR=${SDKDIR}; fi